// <auto-generated />
namespace BluParking.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Required_Placa : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Required_Placa));
        
        string IMigrationMetadata.Id
        {
            get { return "201808170105321_Required_Placa"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
