// <auto-generated />
namespace BluParking.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DisplayName_Preco8 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DisplayName_Preco8));
        
        string IMigrationMetadata.Id
        {
            get { return "201808190343086_DisplayName_Preco8"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
