// <auto-generated />
namespace BluParking.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Colecao_Precos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Colecao_Precos));
        
        string IMigrationMetadata.Id
        {
            get { return "201808170128072_Colecao_Precos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
